# Generated by Django 6.0.1 on 2026-01-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
